wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.9
    framework: huggingface
    huggingface_version: 4.24.0
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.7
    start_time: 1704924075.502919
    t:
      1:
      - 1
      - 3
      - 5
      - 11
      - 41
      - 49
      - 53
      - 55
      2:
      - 1
      - 3
      - 5
      - 11
      - 41
      - 49
      - 53
      - 55
      3:
      - 13
      - 15
      - 23
      4: 3.9.7
      5: 0.13.9
      6: 4.24.0
      8:
      - 5
